<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['name' => 'Albania', 'code' => 'ALB', 'phone_code' => '+355', 'continent' => 'Europe'],
            ['name' => 'Andorra', 'code' => 'AND', 'phone_code' => '+376', 'continent' => 'Europe'],
            ['name' => 'Armenia', 'code' => 'ARM', 'phone_code' => '+374', 'continent' => 'Europe'],
            ['name' => 'Austria', 'code' => 'AUT', 'phone_code' => '+43', 'continent' => 'Europe'],
            ['name' => 'Azerbaijan', 'code' => 'AZE', 'phone_code' => '+994', 'continent' => 'Europe'],
            ['name' => 'Belarus', 'code' => 'BLR', 'phone_code' => '+375', 'continent' => 'Europe'],
            ['name' => 'Belgium', 'code' => 'BEL', 'phone_code' => '+32', 'continent' => 'Europe'],
            ['name' => 'Bosnia and Herzegovina', 'code' => 'BIH', 'phone_code' => '+387', 'continent' => 'Europe'],
            ['name' => 'Bulgaria', 'code' => 'BGR', 'phone_code' => '+359', 'continent' => 'Europe'],
            ['name' => 'Croatia', 'code' => 'HRV', 'phone_code' => '+385', 'continent' => 'Europe'],
            ['name' => 'Cyprus', 'code' => 'CYP', 'phone_code' => '+357', 'continent' => 'Europe'],
            ['name' => 'Czech Republic', 'code' => 'CZE', 'phone_code' => '+420', 'continent' => 'Europe'],
            ['name' => 'Denmark', 'code' => 'DNK', 'phone_code' => '+45', 'continent' => 'Europe'],
            ['name' => 'Estonia', 'code' => 'EST', 'phone_code' => '+372', 'continent' => 'Europe'],
            ['name' => 'Finland', 'code' => 'FIN', 'phone_code' => '+358', 'continent' => 'Europe'],
            ['name' => 'France', 'code' => 'FRA', 'phone_code' => '+33', 'continent' => 'Europe'],
            ['name' => 'Georgia', 'code' => 'GEO', 'phone_code' => '+995', 'continent' => 'Europe'],
            ['name' => 'Germany', 'code' => 'DEU', 'phone_code' => '+49', 'continent' => 'Europe'],
            ['name' => 'Greece', 'code' => 'GRC', 'phone_code' => '+30', 'continent' => 'Europe'],
            ['name' => 'Hungary', 'code' => 'HUN', 'phone_code' => '+36', 'continent' => 'Europe'],
            ['name' => 'Iceland', 'code' => 'ISL', 'phone_code' => '+354', 'continent' => 'Europe'],
            ['name' => 'Ireland', 'code' => 'IRL', 'phone_code' => '+353', 'continent' => 'Europe'],
            ['name' => 'Italy', 'code' => 'ITA', 'phone_code' => '+39', 'continent' => 'Europe'],
            ['name' => 'Latvia', 'code' => 'LVA', 'phone_code' => '+371', 'continent' => 'Europe'],
            ['name' => 'Lithuania', 'code' => 'LTU', 'phone_code' => '+370', 'continent' => 'Europe'],
            ['name' => 'Luxembourg', 'code' => 'LUX', 'phone_code' => '+352', 'continent' => 'Europe'],
            ['name' => 'Malta', 'code' => 'MLT', 'phone_code' => '+356', 'continent' => 'Europe'],
            ['name' => 'Moldova', 'code' => 'MDA', 'phone_code' => '+373', 'continent' => 'Europe'],
            ['name' => 'Monaco', 'code' => 'MCO', 'phone_code' => '+377', 'continent' => 'Europe'],
            ['name' => 'Montenegro', 'code' => 'MNE', 'phone_code' => '+382', 'continent' => 'Europe'],
            ['name' => 'Netherlands', 'code' => 'NLD', 'phone_code' => '+31', 'continent' => 'Europe'],
            ['name' => 'North Macedonia', 'code' => 'MKD', 'phone_code' => '+389', 'continent' => 'Europe'],
            ['name' => 'Norway', 'code' => 'NOR', 'phone_code' => '+47', 'continent' => 'Europe'],
            ['name' => 'Poland', 'code' => 'POL', 'phone_code' => '+48', 'continent' => 'Europe'],
            ['name' => 'Portugal', 'code' => 'PRT', 'phone_code' => '+351', 'continent' => 'Europe'],
            ['name' => 'Romania', 'code' => 'ROU', 'phone_code' => '+40', 'continent' => 'Europe'],
            ['name' => 'Russia', 'code' => 'RUS', 'phone_code' => '+7', 'continent' => 'Europe'],
            ['name' => 'San Marino', 'code' => 'SMR', 'phone_code' => '+378', 'continent' => 'Europe'],
            ['name' => 'Serbia', 'code' => 'SRB', 'phone_code' => '+381', 'continent' => 'Europe'],
            ['name' => 'Slovakia', 'code' => 'SVK', 'phone_code' => '+421', 'continent' => 'Europe'],
            ['name' => 'Slovenia', 'code' => 'SVN', 'phone_code' => '+386', 'continent' => 'Europe'],
            ['name' => 'Spain', 'code' => 'ESP', 'phone_code' => '+34', 'continent' => 'Europe'],
            ['name' => 'Sweden', 'code' => 'SWE', 'phone_code' => '+46', 'continent' => 'Europe'],
            ['name' => 'Switzerland', 'code' => 'CHE', 'phone_code' => '+41', 'continent' => 'Europe'],
            ['name' => 'Ukraine', 'code' => 'UKR', 'phone_code' => '+380', 'continent' => 'Europe'],
            ['name' => 'United Kingdom', 'code' => 'GBR', 'phone_code' => '+44', 'continent' => 'Europe'],
            ['name' => 'Vatican City', 'code' => 'VAT', 'phone_code' => '+379', 'continent' => 'Europe'],
            ['name' => 'Algeria', 'code' => 'DZA', 'phone_code' => '+213', 'continent' => 'Africa'],
            ['name' => 'Angola', 'code' => 'AGO', 'phone_code' => '+244', 'continent' => 'Africa'],
            ['name' => 'Benin', 'code' => 'BEN', 'phone_code' => '+229', 'continent' => 'Africa'],
            ['name' => 'Botswana', 'code' => 'BWA', 'phone_code' => '+267', 'continent' => 'Africa'],
            ['name' => 'Burkina Faso', 'code' => 'BFA', 'phone_code' => '+226', 'continent' => 'Africa'],
            ['name' => 'Burundi', 'code' => 'BDI', 'phone_code' => '+257', 'continent' => 'Africa'],
            ['name' => 'Cabo Verde', 'code' => 'CPV', 'phone_code' => '+238', 'continent' => 'Africa'],
            ['name' => 'Cameroon', 'code' => 'CMR', 'phone_code' => '+237', 'continent' => 'Africa'],
            ['name' => 'Central African Republic', 'code' => 'CAF', 'phone_code' => '+236', 'continent' => 'Africa'],
            ['name' => 'Chad', 'code' => 'TCD', 'phone_code' => '+235', 'continent' => 'Africa'],
            ['name' => 'Comoros', 'code' => 'COM', 'phone_code' => '+269', 'continent' => 'Africa'],
            ['name' => 'Congo', 'code' => 'COG', 'phone_code' => '+242', 'continent' => 'Africa'],
            ['name' => 'Democratic Republic of the Congo', 'code' => 'COD', 'phone_code' => '+243', 'continent' => 'Africa'],
            ['name' => 'Djibouti', 'code' => 'DJI', 'phone_code' => '+253', 'continent' => 'Africa'],
            ['name' => 'Egypt', 'code' => 'EGY', 'phone_code' => '+20', 'continent' => 'Africa'],
            ['name' => 'Equatorial Guinea', 'code' => 'GNQ', 'phone_code' => '+240', 'continent' => 'Africa'],
            ['name' => 'Eritrea', 'code' => 'ERI', 'phone_code' => '+291', 'continent' => 'Africa'],
            ['name' => 'Eswatini', 'code' => 'SWZ', 'phone_code' => '+268', 'continent' => 'Africa'],
            ['name' => 'Ethiopia', 'code' => 'ETH', 'phone_code' => '+251', 'continent' => 'Africa'],
            ['name' => 'Gabon', 'code' => 'GAB', 'phone_code' => '+241', 'continent' => 'Africa'],
            ['name' => 'Gambia', 'code' => 'GMB', 'phone_code' => '+220', 'continent' => 'Africa'],
            ['name' => 'Ghana', 'code' => 'GHA', 'phone_code' => '+233', 'continent' => 'Africa'],
            ['name' => 'Guinea', 'code' => 'GIN', 'phone_code' => '+224', 'continent' => 'Africa'],
            ['name' => 'Guinea-Bissau', 'code' => 'GNB', 'phone_code' => '+245', 'continent' => 'Africa'],
            ['name' => 'Ivory Coast', 'code' => 'CIV', 'phone_code' => '+225', 'continent' => 'Africa'],
            ['name' => 'Kenya', 'code' => 'KEN', 'phone_code' => '+254', 'continent' => 'Africa'],
            ['name' => 'Lesotho', 'code' => 'LSO', 'phone_code' => '+266', 'continent' => 'Africa'],
            ['name' => 'Liberia', 'code' => 'LBR', 'phone_code' => '+231', 'continent' => 'Africa'],
            ['name' => 'Libya', 'code' => 'LBY', 'phone_code' => '+218', 'continent' => 'Africa'],
            ['name' => 'Madagascar', 'code' => 'MDG', 'phone_code' => '+261', 'continent' => 'Africa'],
            ['name' => 'Malawi', 'code' => 'MWI', 'phone_code' => '+265', 'continent' => 'Africa'],
            ['name' => 'Mali', 'code' => 'MLI', 'phone_code' => '+223', 'continent' => 'Africa'],
            ['name' => 'Mauritania', 'code' => 'MRT', 'phone_code' => '+222', 'continent' => 'Africa'],
            ['name' => 'Mauritius', 'code' => 'MUS', 'phone_code' => '+230', 'continent' => 'Africa'],
            ['name' => 'Morocco', 'code' => 'MAR', 'phone_code' => '+212', 'continent' => 'Africa'],
            ['name' => 'Mozambique', 'code' => 'MOZ', 'phone_code' => '+258', 'continent' => 'Africa'],
            ['name' => 'Namibia', 'code' => 'NAM', 'phone_code' => '+264', 'continent' => 'Africa'],
            ['name' => 'Niger', 'code' => 'NER', 'phone_code' => '+227', 'continent' => 'Africa'],
            ['name' => 'Nigeria', 'code' => 'NGA', 'phone_code' => '+234', 'continent' => 'Africa'],
            ['name' => 'Rwanda', 'code' => 'RWA', 'phone_code' => '+250', 'continent' => 'Africa'],
            ['name' => 'São Tomé and Príncipe', 'code' => 'STP', 'phone_code' => '+239', 'continent' => 'Africa'],
            ['name' => 'Senegal', 'code' => 'SEN', 'phone_code' => '+221', 'continent' => 'Africa'],
            ['name' => 'Seychelles', 'code' => 'SYC', 'phone_code' => '+248', 'continent' => 'Africa'],
            ['name' => 'Sierra Leone', 'code' => 'SLE', 'phone_code' => '+232', 'continent' => 'Africa'],
            ['name' => 'Somalia', 'code' => 'SOM', 'phone_code' => '+252', 'continent' => 'Africa'],
            ['name' => 'South Africa', 'code' => 'ZAF', 'phone_code' => '+27', 'continent' => 'Africa'],
            ['name' => 'South Sudan', 'code' => 'SSD', 'phone_code' => '+211', 'continent' => 'Africa'],
            ['name' => 'Sudan', 'code' => 'SDN', 'phone_code' => '+249', 'continent' => 'Africa'],
            ['name' => 'Togo', 'code' => 'TGO', 'phone_code' => '+228', 'continent' => 'Africa'],
            ['name' => 'Tunisia', 'code' => 'TUN', 'phone_code' => '+216', 'continent' => 'Africa'],
            ['name' => 'Uganda', 'code' => 'UGA', 'phone_code' => '+256', 'continent' => 'Africa'],
            ['name' => 'Zambia', 'code' => 'ZMB', 'phone_code' => '+260', 'continent' => 'Africa'],
            ['name' => 'Zimbabwe', 'code' => 'ZWE', 'phone_code' => '+263', 'continent' => 'Africa'],
            // Amérique du Nord
            ['name' => 'Canada', 'code' => 'CAN', 'phone_code' => '+1', 'continent' => 'America'],
            ['name' => 'United States', 'code' => 'USA', 'phone_code' => '+1', 'continent' => 'America'],
            ['name' => 'Mexico', 'code' => 'MEX', 'phone_code' => '+52', 'continent' => 'America'],
            
            // Amérique centrale
            ['name' => 'Guatemala', 'code' => 'GTM', 'phone_code' => '+502', 'continent' => 'America'],
            ['name' => 'Honduras', 'code' => 'HND', 'phone_code' => '+504', 'continent' => 'America'],
            ['name' => 'El Salvador', 'code' => 'SLV', 'phone_code' => '+503', 'continent' => 'America'],
            ['name' => 'Costa Rica', 'code' => 'CRI', 'phone_code' => '+506', 'continent' => 'America'],
            ['name' => 'Panama', 'code' => 'PAN', 'phone_code' => '+507', 'continent' => 'America'],

            // Caraïbes
            ['name' => 'Cuba', 'code' => 'CUB', 'phone_code' => '+53', 'continent' => 'America'],
            ['name' => 'Dominican Republic', 'code' => 'DOM', 'phone_code' => '+1-809', 'continent' => 'America'],
            ['name' => 'Haiti', 'code' => 'HTI', 'phone_code' => '+509', 'continent' => 'America'],
            ['name' => 'Jamaica', 'code' => 'JAM', 'phone_code' => '+1-876', 'continent' => 'America'],
            ['name' => 'Trinidad and Tobago', 'code' => 'TTO', 'phone_code' => '+1-868', 'continent' => 'America'],

            // Amérique du Sud
            ['name' => 'Argentina', 'code' => 'ARG', 'phone_code' => '+54', 'continent' => 'America'],
            ['name' => 'Bolivia', 'code' => 'BOL', 'phone_code' => '+591', 'continent' => 'America'],
            ['name' => 'Brazil', 'code' => 'BRA', 'phone_code' => '+55', 'continent' => 'America'],
            ['name' => 'Chile', 'code' => 'CHL', 'phone_code' => '+56', 'continent' => 'America'],
            ['name' => 'Colombia', 'code' => 'COL', 'phone_code' => '+57', 'continent' => 'America'],
            ['name' => 'Ecuador', 'code' => 'ECU', 'phone_code' => '+593', 'continent' => 'America'],
            ['name' => 'Guyana', 'code' => 'GUY', 'phone_code' => '+592', 'continent' => 'America'],
            ['name' => 'Paraguay', 'code' => 'PRY', 'phone_code' => '+595', 'continent' => 'America'],
            ['name' => 'Peru', 'code' => 'PER', 'phone_code' => '+51', 'continent' => 'America'],
            ['name' => 'Suriname', 'code' => 'SUR', 'phone_code' => '+597', 'continent' => 'America'],
            ['name' => 'Uruguay', 'code' => 'URY', 'phone_code' => '+598', 'continent' => 'America'],
            ['name' => 'Venezuela', 'code' => 'VEN', 'phone_code' => '+58', 'continent' => 'America'],
            // Asie de l'Est
            ['name' => 'China', 'code' => 'CHN', 'phone_code' => '+86', 'continent' => 'Asia'],
            ['name' => 'Japan', 'code' => 'JPN', 'phone_code' => '+81', 'continent' => 'Asia'],
            ['name' => 'South Korea', 'code' => 'KOR', 'phone_code' => '+82', 'continent' => 'Asia'],
            ['name' => 'North Korea', 'code' => 'PRK', 'phone_code' => '+850', 'continent' => 'Asia'],
            ['name' => 'Mongolia', 'code' => 'MNG', 'phone_code' => '+976', 'continent' => 'Asia'],
            
            // Asie du Sud-Est
            ['name' => 'Indonesia', 'code' => 'IDN', 'phone_code' => '+62', 'continent' => 'Asia'],
            ['name' => 'Malaysia', 'code' => 'MYS', 'phone_code' => '+60', 'continent' => 'Asia'],
            ['name' => 'Singapore', 'code' => 'SGP', 'phone_code' => '+65', 'continent' => 'Asia'],
            ['name' => 'Thailand', 'code' => 'THA', 'phone_code' => '+66', 'continent' => 'Asia'],
            ['name' => 'Vietnam', 'code' => 'VNM', 'phone_code' => '+84', 'continent' => 'Asia'],
            ['name' => 'Philippines', 'code' => 'PHL', 'phone_code' => '+63', 'continent' => 'Asia'],
            ['name' => 'Brunei', 'code' => 'BRN', 'phone_code' => '+673', 'continent' => 'Asia'],
            ['name' => 'Myanmar', 'code' => 'MMR', 'phone_code' => '+95', 'continent' => 'Asia'],
            ['name' => 'Laos', 'code' => 'LAO', 'phone_code' => '+856', 'continent' => 'Asia'],
            ['name' => 'Cambodia', 'code' => 'KHM', 'phone_code' => '+855', 'continent' => 'Asia'],
            ['name' => 'Timor-Leste', 'code' => 'TLS', 'phone_code' => '+670', 'continent' => 'Asia'],

            // Asie du Sud
            ['name' => 'India', 'code' => 'IND', 'phone_code' => '+91', 'continent' => 'Asia'],
            ['name' => 'Pakistan', 'code' => 'PAK', 'phone_code' => '+92', 'continent' => 'Asia'],
            ['name' => 'Nepal', 'code' => 'NPL', 'phone_code' => '+977', 'continent' => 'Asia'],
            ['name' => 'Bangladesh', 'code' => 'BGD', 'phone_code' => '+880', 'continent' => 'Asia'],
            ['name' => 'Sri Lanka', 'code' => 'LKA', 'phone_code' => '+94', 'continent' => 'Asia'],
            ['name' => 'Maldives', 'code' => 'MDV', 'phone_code' => '+960', 'continent' => 'Asia'],
            ['name' => 'Bhutan', 'code' => 'BTN', 'phone_code' => '+975', 'continent' => 'Asia'],

            // Asie centrale
            ['name' => 'Kazakhstan', 'code' => 'KAZ', 'phone_code' => '+7', 'continent' => 'Asia'],
            ['name' => 'Uzbekistan', 'code' => 'UZB', 'phone_code' => '+998', 'continent' => 'Asia'],
            ['name' => 'Turkmenistan', 'code' => 'TKM', 'phone_code' => '+993', 'continent' => 'Asia'],
            ['name' => 'Kyrgyzstan', 'code' => 'KGZ', 'phone_code' => '+996', 'continent' => 'Asia'],
            ['name' => 'Tajikistan', 'code' => 'TJK', 'phone_code' => '+992', 'continent' => 'Asia'],

            // Asie de l'Ouest
            ['name' => 'Saudi Arabia', 'code' => 'SAU', 'phone_code' => '+966', 'continent' => 'Asia'],
            ['name' => 'Turkey', 'code' => 'TUR', 'phone_code' => '+90', 'continent' => 'Asia'],
            ['name' => 'Iran', 'code' => 'IRN', 'phone_code' => '+98', 'continent' => 'Asia'],
            ['name' => 'Iraq', 'code' => 'IRQ', 'phone_code' => '+964', 'continent' => 'Asia'],
            ['name' => 'Syria', 'code' => 'SYR', 'phone_code' => '+963', 'continent' => 'Asia'],
            ['name' => 'Jordan', 'code' => 'JOR', 'phone_code' => '+962', 'continent' => 'Asia'],
            ['name' => 'Lebanon', 'code' => 'LBN', 'phone_code' => '+961', 'continent' => 'Asia'],
            ['name' => 'Israel', 'code' => 'ISR', 'phone_code' => '+972', 'continent' => 'Asia'],
            ['name' => 'Kuwait', 'code' => 'KWT', 'phone_code' => '+965', 'continent' => 'Asia'],
            ['name' => 'Bahrain', 'code' => 'BHR', 'phone_code' => '+973', 'continent' => 'Asia'],
            ['name' => 'Qatar', 'code' => 'QAT', 'phone_code' => '+974', 'continent' => 'Asia'],
            ['name' => 'United Arab Emirates', 'code' => 'ARE', 'phone_code' => '+971', 'continent' => 'Asia'],
            ['name' => 'Oman', 'code' => 'OMN', 'phone_code' => '+968', 'continent' => 'Asia'],

            // Asie du Sud-Est
            ['name' => 'Afghanistan', 'code' => 'AFG', 'phone_code' => '+93', 'continent' => 'Asia'],
            ['name' => 'Yemen', 'code' => 'YEM', 'phone_code' => '+967', 'continent' => 'Asia'],
        ];

        DB::table('countries')->insert($countries);
    }
}
